name = "Square Sort"
uuid = "b4cd1eb8-1e24-11e8-3319-93036a3eb9f3"
version = "0.1.0"
authors = ["Raul Bruno Santos Lima <raulbrunoslima@gmail.com>"]

[deps]
DataStructures = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18"
SortingAlgorithms = "1.0.1"

[compat]
julia = "1.7"
DataStructures = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18"
SortingAlgorithms = "1.0.1"

[targets]
test = ['Test']